### ISSUE TITLE
Homologação do dashboard

### ISSUE THREAD

**Issue by ricardopoppi** [cidadedemocratica/ej-server#141]
- [x] Informar a url destination a que os dados se referem (gráficos 1 e 2) - no futuro isso pode virar um campo aberto ou dropdown pro usuário do dash selecionar a url, mas por agora pode ser apenas informativo -> [Nova issue](https://github.com/cidadedemocratica/ej-server/issues/147)

- [ ] No gráfico 2 permitir um filtro por email válido (pode ser o checkbox proposto nos slides do escopo) - isso vai permitir detectar a aquisição qualificada de já convertidos no mautic -> [Nova issue](https://github.com/cidadedemocratica/ej-server/issues/148)

- [x] No gráfico 3 incluir o indicador de participação (que havia sido definido como um novo gráfico de barra independente

- [x] No gráfico 3, permitir a ordenação por convergência (atualmente só é possível ordenar por concorda, discorda e pulo)

- [x] No gráfico 3, informar o id da conversa (num primeiro momento apenas informativo, para depois que for implementado o suporte a múltiplas conversas o usuário poder alterar o id dependendo da conversa que deseja visualizar) -> [Nova issue](https://github.com/cidadedemocratica/ej-server/issues/145)

- [ ] O dashboard apresenta um erro quando as opções de utm_source: l.instagram.com, m.facebook.com e facebook.com são selecionadas. Erro: `Callback error updating query_explorer_filters.children`

- [ ] Quando o utm_medium = ejtweet ou o utm_campaign = datafolha28abril é selecionado o circulo do primeiro gráfico (Engajamento vs Aquisição (EJ)) se transforma num retângulo

UPDATE PÓS REUNIÃO DE 31/JULHO

- [x] Incluir o índice de participação (nova barra) nas "células" onde estão os índices geral e por cluster

- [x] Solução para visualização: diminuir a coluna do "comentário_id" e bloquear as duas primeiras colunas (comentário_id e comentário) no scroll lateral (foi aventada a possibilidade de usar duas tabelas para isso) -> [Nova issue](https://github.com/cidadedemocratica/ej-server/issues/144)

- [x] Avaliar qual a melhor forma para poder resetar o campo de período. Os outros campos exibem essa possibilidade mas o de período só é possível resetar recarregando a página do dashboard inteira

**Comment by MarthaDs** [comment]
@ricardopoppi  não consegui reproduzir os erros mencionados na issue. Você  verificar se o erro persiste mesmo com as novas atualizações, por favor.

**Comment by ricardopoppi** [comment]
@MarthaDs realmente também não aconteceu mais. O que parece é que a fonte de dados do dashboard não está mais obtendo os sources "l.instagram.com" e "m.facebook.com" e nem os parametros utm_medium = ejtweet ou o utm_campaign = datafolha28abril.

Acho que isso pode ter relação com o fato dos dados não default serem mais recentes, pois esses parâmetros dizem respeito a primeira fase da coleta realizada em abril e maio.

O ideal seria atualizar o airflow para ir buscar esses dados mais antigos, pelo menos a partir de 17/abril que foi quando iniciamos a coleta. Só assim a gente vai poder ter certeza de que esses erros não vão aparecer mais

**Comment by MarthaDs** [comment]
> @MarthaDs realmente também não aconteceu mais pra mim também. O que parece é que a fonte de dados do dashboard não está mais obtendo os sources "l.instagram.com" e "m.facebook.com" e nem os parametros utm_medium = ejtweet ou o utm_campaign = datafolha28abril.
> 
> Acho que isso pode ter relação com o fato dos dados do airflow serem mais recentes, pois esses parâmetros dizem respeito a primeira fase da coleta realizada em abril e maio.
> 
> O ideal seria atualizar o airflow para ir buscar esses dados mais antigos, pelo menos a partir de 17/abril que foi quando iniciamos a coleta. Só assim a gente vai poder ter certeza de que esses erros não vão aparecer mais

@davidCarlos você conseguiria testar os filtros com os dados antigos, por favor

**Comment by davidCarlos** [comment]
@MarthaDs amanhã eu rodo uma coleta puxando os dados mais antigos do analytics, e faço essa validação.
